PrototypeApp/PrototypeApp.Web/Controllers/BlogPostManagementController.cs
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using PagedList;
using PrototypeApp.BLL.DTOs;
using PrototypeApp.BLL.Filters.FilterParameters;
using PrototypeApp.BLL.Services.Abstract;
using PrototypeApp.Web.Helpers;
using PrototypeApp.Web.Models.BlogPosts;
using PrototypeApp.Web.Resources;
using PrototypeApp.Web.ViewModels;

namespace PrototypeApp.Web.Controllers
{
    [Authorize(Roles = "admin")]
    public class BlogPostManagementController : Controller
    {
        private IBlogPostService blogPostService;

        public BlogPostManagementController(IBlogPostService blogPostService)
        {
            this.blogPostService = blogPostService;
        }

        [AllowAnonymous]
        public ActionResult Get(string alias)
        {
            var requestedPost = this.blogPostService.GetBlogPostByAlias(alias);
            return this.View(Mapper.Map<BlogPostDTO, BlogPostModel>(requestedPost));
        }

        public ActionResult GetPosts(GetPostsModel getPostsModel)
        {
            if (!ModelState.IsValid)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            int totalNumberOfPosts;
            var pagination = getPostsModel.PaginationModel;
            if (!PaginationHelper.IsPaginationModelFilled(pagination))
            {
                PaginationHelper.FillPaginationWithDefaultGridParameters(pagination);
            }

            var filterParameters = Mapper.Map<BlogPostFilterParametersModel, BlogPostFilterParameters>(getPostsModel.FilterParameters);
            var requestedPosts = this.blogPostService.Get(filterParameters,
                pagination.RecordsToSkip,
                pagination.RecordsPerPage,
                out totalNumberOfPosts).ToList();

            StaticPagedList<BlogPostDTO> blogPostsList = new StaticPagedList<BlogPostDTO>(requestedPosts,
                pagination.PageNumber,
                pagination.RecordsPerPage,
                totalNumberOfPosts);

            return this.View("BlogPosts", new BlogPostsViewModel() { BlogPosts = blogPostsList, FilterParameters = filterParameters });
        }

        [HttpGet]
        public ActionResult Add()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<ActionResult> Add(BlogPostModel blogPostModel)
        {
            this.FillModelStateBlogPostErrors(blogPostModel);
            if (!ModelState.IsValid)
            {
                return this.View(blogPostModel);
            }

            await this.blogPostService.Add(Mapper.Map<BlogPostModel, BlogPostDTO>(blogPostModel), User.Identity.Name);
            return this.RedirectToAction("GetPosts");
        }

        [HttpGet]
        public ActionResult Edit(int postId)
        {
            var requestedBlogPost = this.blogPostService.GetBlogPostById(postId);
            return this.View(Mapper.Map<BlogPostDTO, BlogPostModel>(requestedBlogPost));
        }

        [HttpPost]
        public async Task<ActionResult> Edit(BlogPostModel blogPostModel)
        {
            this.FillModelStateBlogPostErrors(blogPostModel);
            if (!ModelState.IsValid)
            {
                return this.View(blogPostModel);
            }

            await this.blogPostService.Edit(Mapper.Map<BlogPostModel, BlogPostDTO>(blogPostModel), User.Identity.Name);
            return this.RedirectToAction("GetPosts");
        }

        [HttpDelete]
        public async Task<ActionResult> Delete(int postId)
        {
            await this.blogPostService.Delete(postId, User.Identity.Name);
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        private void FillModelStateBlogPostErrors(BlogPostModel blogPostModel)
        {
            string aliasModelStateKey = "Alias";
            string titleModelStateKey = "Title";

            if (this.blogPostService.IsAliasTaken(blogPostModel.Alias, blogPostModel.Id))
            {
                this.ModelState.AddModelError(aliasModelStateKey, ValidationMessages.AliasIsAlredyTaken);
            }

            if (this.blogPostService.IsTitleTaken(blogPostModel.Title, blogPostModel.Id))
            {
                this.ModelState.AddModelError(titleModelStateKey, ValidationMessages.TitleIsAlreadyTaken);
            }
        }
    }
}

PrototypeApp/PrototypeApp.Web/Controllers/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using PagedList;
using PrototypeApp.BLL.DTOs;
using PrototypeApp.BLL.Filters.FilterParameters;
using PrototypeApp.BLL.Services.Abstract;
using PrototypeApp.Web.Helpers;
using PrototypeApp.Web.Models.Users;
using PrototypeApp.Web.ViewModels;

namespace PrototypeApp.Web.Controllers
{
    [Authorize(Roles = "admin")]
    public class UserManagementController : Controller
    {
        private const string EmailModelStateKey = "Email";
        private readonly IUserManagementService userManagementService;

        public UserManagementController(IUserManagementService userManagementService)
        {
            this.userManagementService = userManagementService;
        }

        public ActionResult GetUsers(GetUsersModel getUsersModel)
        {
            if (ModelState.IsValid)
            {
                int totalNumberOfUsers;
                var pagination = getUsersModel.PaginationModel;
                if (!PaginationHelper.IsPaginationModelFilled(pagination))
                {
                    PaginationHelper.FillPaginationWithDefaultGridParameters(pagination);
                }

                var filterParameters = Mapper.Map<UserFilterParametersModel, UsersFilterParameters>(getUsersModel.UserFilterParametersModel);
                var requestedUsers = this.userManagementService.Get(filterParameters,
                    pagination.RecordsToSkip,
                    pagination.RecordsPerPage,
                    out totalNumberOfUsers).ToList();

                StaticPagedList<UserDTO> userList = new StaticPagedList<UserDTO>(requestedUsers,
                    pagination.PageNumber,
                    pagination.RecordsPerPage,
                    totalNumberOfUsers);

                return this.View("Users",
                    new GetUsersViewModel()
                    {
                        Users = userList,
                        UserFilterParameters = filterParameters
                    });
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        [HttpPost]
        public async Task<ActionResult> AddUser(AddUserModel addUserModal)
        {
            if (ModelState.IsValid)
            {
                var user = Mapper.Map<AddUserModel, UserDTO>(addUserModal);
                var result = await this.userManagementService.AddUserAsync(user, User.Identity.Name);
                if (result.Succeeded)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.OK);
                }

                IdentityHelper.SetModelStateErrors(this.ModelState, result, EmailModelStateKey);
            }

            Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return this.Json(ModelState.ToDictionary(kvp => kvp.Key, kvp => kvp.Value.Errors.ToList()));
        }

        [HttpPut]
        public async Task<ActionResult> EditUser(EditedUserModel editedUserModel)
        {
            if (ModelState.IsValid)
            {
                var mappedUserDTO = Mapper.Map<EditedUserModel, UserDTO>(editedUserModel);
                var userEditingResult = await this.userManagementService.EditUserAsync(mappedUserDTO, User.Identity.Name);
                if (userEditingResult.Succeeded)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.OK);
                }

                IdentityHelper.SetModelStateErrors(this.ModelState, userEditingResult, EmailModelStateKey);
            }

            Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return this.Json(ModelState.ToDictionary(kvp => kvp.Key, kvp => kvp.Value.Errors.ToList()));
        }

        [HttpDelete]
        public async Task<ActionResult> DeleteUser(string userId)
        {
            var result = await this.userManagementService.DeleteAsync(userId, User.Identity.Name);
            if (result.Succeeded)
            {
                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }
    }
}

PrototypeApp/PrototypeApp.Web/Views/Shared/AdministrationLayout.cshtml
@{
    string currentActionName = this.ViewContext.RouteData.Values["action"].ToString();
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/AppStyles")
    @Styles.Render("~/Content/Sidebar")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/eModal")
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top" id="navbar-administration">
    <div class="pull-left">
        @Html.ActionLink("Home", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
    </div>
    <div class="pull-right">
        @Html.Partial("LoginPartial")
    </div>
</div>
    <div class="container-fluid height-match-parent">
        <div class="row height-match-parent">
            <div class="col-xs-2 height-match-parent" id="siderbar-nav-block">
                <nav class="navbar navbar-inverse sidebar" role="navigation">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li>
                                <a href="@Url.Action("Index", "Home")">
                                    Home<span class="menu-icon pull-right hidden-xs showopacity glyphicon glyphicon-home"></span>
                                </a>
                            </li>
                            <li class="@(currentActionName == "GetUsers" ? "active" : "")">
                                <a href="@Url.Action("GetUsers", "UserManagement")">
                                    Users<span class="menu-icon pull-right hidden-xs showopacity glyphicon glyphicon-user"/>
                                </a>
                            </li>
                            <li class="@(currentActionName == "GetPosts" ? "active" : "")">
                                <a href="@Url.Action("GetPosts", "BlogPostManagement")">
                                    Blog posts<span class="menu-icon pull-right hidden-xs showopacity glyphicon glyphicon-picture"/>
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
            <div class="col-xs-10" id="contentContainer">
                @RenderBody()
            </div>
        </div>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

PrototypeApp/PrototypeApp.Web/Views/Shared/LoginPartial.cshtml
@using Microsoft.AspNet.Identity
@{
    string currentUserName = "";
    if (User.Identity.IsAuthenticated)
    {
        currentUserName = User.Identity.GetUserName();
    }
}

@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("Logout", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
        @Html.AntiForgeryToken()

        <ul class="nav navbar-nav navbar-right">
            <li>
                @Html.ActionLink("You are logged as " + @currentUserName + " (Log out)", "Logout", "Account")
            </li>
        </ul>
    }
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li>@Html.ActionLink("Register", "Register", "Account")</li>
        <li>@Html.ActionLink("Log in", "Login", "Account")</li>
    </ul>
}

PrototypeApp/PrototypeApp.Web/Views/Shared/_Layout.cshtml
@{
    var isCurrentUserAdministrator = User.Identity.IsAuthenticated && User.IsInRole("admin");
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/AppStyles")
    @Styles.Render("~/Content/Sidebar")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Blog", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Credentials", "Credentials", "Home")</li>
                    @if (isCurrentUserAdministrator)
                    {
                        <li>@Html.ActionLink("Administration", "GetUsers", "UserManagement")</li>
                    }
                </ul>
                @Html.Partial("LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>